### ISSUE TITLE
fix up CI

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_PCF8574#2]
this library is working - needs CI fix up before release

@tekktrik is this something you can look at?
also, cookiecutter has 2 defaults that are not valid:
https://github.com/adafruit/Adafruit_CircuitPython_PCF8574/commit/7c19725ecc1aa58448bc0bcc14e23e2ca9276410
and
https://github.com/adafruit/Adafruit_CircuitPython_PCF8574/commit/c20d38e3d7ede4f1e95b6d60205c6e1dc03d82c6
https://github.com/adafruit/Adafruit_CircuitPython_PCF8574/commit/7ee56570de5d13ffaec46a8aa18a449b8856beb7
https://github.com/adafruit/Adafruit_CircuitPython_PCF8574/commit/0c7db13b14164fa54fcdbb44cd8a3daee0e7e233

which needs to be fixed in the cookie repo

**Comment by tekktrik** [comment]
Weird, the cookiecutter has those defaults as you've corrected them, maybe it was fixed after?  The `language` setting definitely needed to be updated though.  PR inbound!

- [Black version at 22.3.0](https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/6675a7d766c425cbbf48e3a11262eb77025e5aaa/%7B%7B%20cookiecutter%20and%20'tmp_repo'%20%7D%7D/.pre-commit-config.yaml#L7)

**Comment by ladyada** [comment]
woops sorry i was using @jepler s msys friendly fork… jeff dya wanna get those tweaks mainlined? i use the cookiecutter a lot

**Comment by ladyada** [comment]
@tekktrik it still needs some formatting, can u take a look? i have to move onto other hardware designs 😌

**Comment by tekktrik** [comment]
Roger roger!

**Comment by tekktrik** [comment]
I don't have permissions to set up the webhook for the RTD docs, so if you want to import the project into RTD that's the only remaining step!  Otherwise if you're busy I'll see if someone else with permissions can.

**Comment by ladyada** [comment]
@tekktrik ok im not 100% sure how to add you to those RTD perms but ideally yah you can do that for me after a library is ready to rock - @tannewt / @kattni mebe you can help with bits?

**Comment by tannewt** [comment]
@tekktrik Do you have an RTD account? I can add you the the CP project so you can add the subproject. We also usually make the blinka account a manager of any new project too.

**Comment by kattni** [comment]
@tekktrik Please ping me directly when you're ready to move forward with RTD. I'll walk you through our process.

**Comment by tekktrik** [comment]
@kattni This library is good for PyPI!  Everything else is set!

**Comment by kattni** [comment]
RTD done!
